
# Название файла, который будет отправляться. Должен находиться в папке с этим config.yml
file: "Server Resource Pack.zip"

server:
  # Будет показываться при вводе команды /rpserver link
  domain: "example.com"
  # Порт HTTP веб-сервера, на котором будет раздаваться ресурспак
  port: 8081

messages:
  usage:
    - " "
    - "&#745c97RPServer &#696969- &#fcfcfcПомощь"
    - " &#696969- &#745c97/rpserver reload &#696969- &#fcfcfcперезагрузить плагин"
    - " &#696969- &#745c97/rpserver link &#696969- &#fcfcfcполучить ссылку на скачивание РП"
    - " &#696969- &#745c97/rpserver hash &#696969- &#fcfcfcполучить хеш"
    - " "
  noPermission: "&#d45079У вас недостаточно прав для выполнения этой команды!"
  reloaded: "&#ace1afПлагин успешно перезагружен!"
  link: "&#745c97RPServer &#696969▸ &#fcfcfcСсылка на скачивание ресурспака: &#745c97http://%domain%:%port%/"
  hash: "&#745c97RPServer &#696969▸ &#fcfcfcХеш ресурспака: &#745c97%hash%"
